drop table LOCATIONS;
create table LOCATIONS
(
    location_ID   int auto_increment
        primary key,
    country         varchar(255) not null,
    city  varchar(255) not null,
    street varchar(255) not null,
    house_number  int not null
);


INSERT INTO `group4`.`locations` (location_ID,country,city,street,house_number)
VALUES
    ('203', 'Israel', 'Beer Sheva', 'Ibn Gabirol', '361'),
    ('204', 'Israel', 'Beer Sheva', 'Rothschild', '229'),
    ('205', 'Israel', 'Haifa', 'Rothschild', '71'),
    ('206', 'Israel', 'Tel Aviv', 'Bograshov Street', '8'),
    ('207', 'Israel', 'Jerusalem', 'Ben Yehuda', '419'),
    ('208', 'Israel', 'Tel Aviv', 'Hayarkon', '59'),
    ('209', 'Israel', 'Jerusalem', 'Herzl', '487'),
    ('210', 'Israel', 'Haifa', 'Arlozoroff', '21'),
    ('211', 'Israel', 'Tel Aviv', 'Ben-Gurion', '186'),
    ('212', 'Israel', 'Haifa', 'Herzl', '78'),
    ('213', 'Israel', 'Tel Aviv', 'Rothschild', '258'),
    ('214', 'Israel', 'Haifa', 'Bograshov Street', '377'),
    ('215', 'Israel', 'Beer Sheva', 'Derekh Hebron', '66'),
    ('216', 'Israel', 'Tel Aviv', 'Dizengoff', '282'),
    ('217', 'Israel', 'Beer Sheva', 'Ben Yehuda', '273'),
    ('218', 'Israel', 'Beer Sheva', 'Levi Eshkol', '193'),
    ('219', 'Israel', 'Tel Aviv', 'Herzl', '155'),
    ('220', 'Israel', 'Haifa', 'Natanzon', '4'),
    ('221', 'Israel', 'Beer Sheva', 'Herzl', '492'),
    ('222', 'Israel', 'Jerusalem', 'Rothschild', '216'),
    ('223', 'Israel', 'Tel Aviv', 'Mendele Mokher Sfarim Mendeli', '5'),
    ('224', 'Israel', 'Beer Sheva', 'Levi Eshkol', '116'),
    ('225', 'Israel', 'Jerusalem', 'Beit Yaakov', '10'),
    ('226', 'Israel', 'Beer Sheva', 'King George', '62'),
    ('227', 'Israel', 'Jerusalem', 'Rothschild', '312'),
    ('228', 'Israel', 'Jerusalem', 'Begin', '461'),
    ('229', 'Israel', 'Jerusalem', 'Rothschild', '4'),
    ('230', 'Israel', 'Jerusalem', 'Ben Yehuda', '61'),
    ('231', 'Israel', 'Beer Sheva', 'Levi Eshkol', '87'),
    ('232', 'Israel', 'Beer Sheva', 'Bograshov Street', '58'),
    ('233', 'Israel', 'Tel Aviv', 'King George', '359'),
    ('234', 'Israel', 'Beer Sheva', 'Herzl', '311'),
    ('235', 'Israel', 'Beer Sheva', 'Herzl', '172'),
    ('236', 'Israel', 'Tel Aviv', 'Levi Eshkol', '495'),
    ('237', 'Israel', 'Beer Sheva', 'Rothschild', '309'),
    ('238', 'Israel', 'Tel Aviv', 'Levi Eshkol', '317'),
    ('239', 'Israel', 'Haifa', 'Ben Yehuda', '234'),
    ('240', 'Israel', 'Jerusalem', 'Bograshov Street', '158'),
    ('241', 'Israel', 'Haifa', 'Ben Yehuda', '381'),
    ('242', 'Israel', 'Tel Aviv', 'Rothschild', '263'),
    ('243', 'Israel', 'Haifa', 'Ben-Gurion', '357'),
    ('244', 'Israel', 'Tel Aviv', 'Ben Yehuda', '165'),
    ('245', 'Israel', 'Tel Aviv', 'Herzl', '447'),
    ('246', 'Israel', 'Tel Aviv', 'Rothschild', '8'),
    ('247', 'Israel', 'Beer Sheva', 'Ben-Gurion', '295'),
    ('248', 'Israel', 'Tel Aviv', 'Arlozoroff', '451'),
    ('249', 'Israel', 'Tel Aviv', 'Ibn Gabirol', '12'),
    ('250', 'Israel', 'Haifa', 'Ben-Gurion', '442'),
    ('251', 'Israel', 'Haifa', 'Arlozoroff', '214'),
    ('252', 'Israel', 'Haifa', 'Levi Eshkol', '263'),
    ('253', 'Israel', 'Jerusalem', 'Bialik Street', '65'),
    ('254', 'Israel', 'Jerusalem', 'Rothschild', '165'),
    ('255', 'Israel', 'Jerusalem', 'Ben Yehuda', '146'),
    ('256', 'Israel', 'Beer Sheva', 'Rothschild', '80'),
    ('257', 'Israel', 'Beer Sheva', 'King George', '322'),
    ('258', 'Israel', 'Tel Aviv', 'Arlozoroff', '318'),
    ('259', 'Israel', 'Haifa', 'Bialik Street', '284'),
    ('260', 'Israel', 'Haifa', 'Bograshov Street', '65'),
    ('261', 'Israel', 'Jerusalem', 'Rothschild', '83'),
    ('262', 'Israel', 'Beer Sheva', 'King George', '458'),
    ('263', 'Israel', 'Jerusalem', 'King George', '189'),
    ('264', 'Israel', 'Beer Sheva', 'Dizengoff', '394'),
    ('265', 'Israel', 'Haifa', 'King George', '335'),
    ('266', 'Israel', 'Haifa', '', '93'),
    ('267', 'Israel', 'Beer Sheva', 'Levi Eshkol', '79'),
    ('268', 'Israel', 'Tel Aviv', 'Balfour', '469'),
    ('269', 'Israel', 'Haifa', 'Ben Yehuda', '493'),
    ('270', 'Israel', 'Haifa', 'Bograshov Street', '447'),
    ('271', 'Israel', 'Tel Aviv', 'Begin', '23'),
    ('272', 'Israel', 'Jerusalem', 'Chopin', '5'),
    ('273', 'Israel', 'Tel Aviv', 'Dizengoff', '316'),
    ('274', 'Israel', 'Haifa', 'Dizengoff', '374'),
    ('275', 'Israel', 'Jerusalem', 'Levi Eshkol', '495'),
    ('276', 'Israel', 'Jerusalem', 'King George', '134'),
    ('277', 'Israel', 'Jerusalem', 'King George', '418'),
    ('278', 'Israel', 'Tel Aviv', 'Levi Eshkol', '154'),
    ('279', 'Israel', 'Tel Aviv', 'Ben Yehuda', '426'),
    ('280', 'Israel', 'Jerusalem', 'Dizengoff', '59'),
    ('281', 'Israel', 'Jerusalem', 'Begin', '356'),
    ('282', 'Israel', 'Beer Sheva', 'Bograshov Street', '51'),
    ('283', 'Israel', 'Beer Sheva', 'Begin', '461'),
    ('284', 'Israel', 'Haifa', 'Levi Eshkol', '489'),
    ('285', 'Israel', 'Haifa', 'Dizengoff', '442'),
    ('286', 'Israel', 'Jerusalem', 'Rothschild', '194'),
    ('287', 'Israel', 'Jerusalem', 'Arlozoroff', '431'),
    ('288', 'Israel', 'Jerusalem', 'Arlozoroff', '471'),
    ('289', 'Israel', 'Tel Aviv', 'Bograshov Street', '90'),
    ('290', 'Israel', 'Tel Aviv', 'Herzl', '204'),
    ('291', 'Israel', 'Jerusalem', 'Ben Yehuda', '175'),
    ('292', 'Israel', 'Jerusalem', 'Ben-Gurion', '24'),
    ('293', 'Israel', 'Jerusalem', 'Rothschild', '6'),
    ('294', 'Israel', 'Haifa', 'King George', '140'),
    ('295', 'Israel', 'Jerusalem', 'Balfour', '72'),
    ('296', 'Israel', 'Tel Aviv', 'Ben-Gurion', '371'),
    ('297', 'Israel', 'Beer Sheva', 'Ben Yehuda', '455'),
    ('298', 'Israel', 'Haifa', 'Dizengoff', '429'),
    ('299', 'Israel', 'Haifa', 'Bograshov Street', '211'),
    ('300', 'Israel', 'Jerusalem', 'Rothschild', '277'),
    ('301', 'Israel', 'Tel Aviv', 'Berkovich', '4'),
    ('302', 'Israel', 'Tel Aviv', 'King George', '72');